# Generated by Django 5.0.3 on 2024-06-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_donor',
            name='td_howtocontact',
        ),
        migrations.AddField(
            model_name='t_donor',
            name='name',
            field=models.CharField(choices=[('select', 'Select'), ('shoes', 'Shoes'), ('clothes', 'Clothes'), ('food items', 'Food Items')], default='select', max_length=50),
        ),
        migrations.AddField(
            model_name='t_donor',
            name='td_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_donor',
            name='td_item',
            field=models.CharField(choices=[('select', 'Select'), ('shoes', 'Shoes'), ('clothes', 'Clothes'), ('food items', 'Food Items')], default='select', max_length=50),
        ),
    ]
