# Generated by Django 5.0.3 on 2024-07-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_t_donor_td_howtocontact_t_donor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_donor',
            name='name',
        ),
        migrations.AlterField(
            model_name='t_donor',
            name='td_item',
            field=models.CharField(blank=True, choices=[('select', 'Select'), ('shoes', 'Shoes'), ('clothes', 'Clothes'), ('food items', 'Food Items')], max_length=50, null=True),
        ),
    ]
