# Generated by Django 5.0.3 on 2024-07-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_t_donor_name_alter_t_donor_td_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_donor',
            name='td_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_donor',
            name='td_item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_donor',
            name='td_item',
            field=models.CharField(blank=True, choices=[('select', 'Select'), ('money', 'Money'), ('clothes', 'Clothes'), ('food items', 'Food Items'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
