# Generated by Django 5.0.3 on 2024-08-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_p_receiver_remove_t_receiver_tr_howtocontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_donor',
            name='D_contactcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p_donor',
            name='D_emailcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p_receiver',
            name='R_contactcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='p_receiver',
            name='R_emailcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_donor',
            name='td_contactcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_donor',
            name='td_emailcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_receiver',
            name='tr_contactcheckbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_receiver',
            name='tr_emailcheckbox',
            field=models.BooleanField(default=False),
        ),
    ]
