# Generated by Django 5.0.3 on 2024-07-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_t_donor_td_email_t_donor_td_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_donor',
            name='td_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
