# Generated by Django 5.0.3 on 2024-07-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_t_donor_td_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_donor',
            name='D_category',
        ),
        migrations.RemoveField(
            model_name='p_donor',
            name='D_regno',
        ),
        migrations.AddField(
            model_name='p_donor',
            name='D_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='p_donor',
            name='D_item',
            field=models.CharField(blank=True, choices=[('select', 'Select'), ('money', 'Money'), ('clothes', 'Clothes'), ('food items', 'Food Items'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='p_donor',
            name='D_item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='p_donor',
            name='D_verify',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
