# Generated by Django 5.0.3 on 2024-10-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_p_donor_d_contactcheckbox_p_donor_d_emailcheckbox_and_more'),
        ('core', '0005_p_donor_d_contactcheckbox_p_donor_d_emailcheckbox_and_more'),
    ]

    operations = [
    ]
