# Generated by Django 5.0.3 on 2024-07-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_p_donor_d_category_remove_p_donor_d_regno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='p_donor',
            name='D_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
